titleOnly: true
commitOnly: false
titleAndCommits: false
scopes:
  - api
  - cmd
  - config
  - contrib
  - docs
  - encoding
  - hack
  - internal
  - log
  - metadata
  - metrics
  - middleware
  - registry
  - selector
  - third_party
  - transport
types:
  - deps
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
